---
title: "3d"
author: "Kristian Maras"
date: "2024-03-13"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(plotly)
source("paths.R")
get_paths()
#Run after building_features.R



#data_type <- "filtered"
#data_type <- "imputed"

get_data <- function(data_type) {
  data <- readRDS(file = here::here(generated_data_path,paste0(data_type,"_aggregate_data.rds")))

# Labels
data <- data  %>% mutate(depth_label = case_when(
  endocardium_scar == 0 & intramural_scar == 0 & epicardial_scar == 0 ~ "NoScar",
  endocardium_scar == 1 ~ "AtLeastEndo",
  endocardium_scar == 0 & intramural_scar == 1  ~ "AtLeastIntra",
  endocardium_scar == 0 & intramural_scar == 0 & epicardial_scar == 1 ~ "epiOnly",
  TRUE ~ "Otherwise"
))  %>% select(-c(endocardium_scar,intramural_scar,epicardial_scar))

return(data)
  
}


plot_all_wavefront <- function(data,select_sheep) {
  data_plot <- data %>% filter(sheep == select_sheep)
  
  fig <- plot_ly(data_plot, x = ~X, y = ~Y, z = ~Z, type = "scatter3d", mode = "markers", marker = list(size = 3),
                  color = ~depth_label, colors = c("red", "blue", "green","black")) %>%
    layout(title = paste0("Sheep",select_sheep))
  
  fig

}

plot_wavefront <- function(select_sheep,select_wavefront) {
  data_plot <- data %>% filter(sheep == select_sheep,WaveFront == select_wavefront)
  
  fig <- plot_ly(data_plot, x = ~X, y = ~Y, z = ~Z, type = "scatter3d", mode = "markers", marker = list(size = 3),
                  color = ~depth_label, colors = c("red", "blue", "green","black")) %>%
    layout(title = paste0("Sheep",select_sheep, "WaveFront ", select_wavefront))
  
  fig

}

data_filtered <- get_data("filtered")
data_imputed <- get_data("imputed")
```

## 3D Plots of the curated labeles (Ground Truth)

These are plots of the labelled data.
These plots can be compared to the prediction_plots that look at prediction accuracy


### Plots of all wavefronts - Imputed Data

```{r}

plot_all_wavefront(data_imputed,"S9")
plot_all_wavefront(data_imputed,"S12")
plot_all_wavefront(data_imputed,"S15")
plot_all_wavefront(data_imputed,"S17")
plot_all_wavefront(data_imputed,"S18")
plot_all_wavefront(data_imputed,"S20")

```

### Plots of all wavefronts - Filtered Data



```{r echo=FALSE}

plot_all_wavefront(data_filtered,"S9")
plot_all_wavefront(data_filtered,"S12")
plot_all_wavefront(data_filtered,"S15")
plot_all_wavefront(data_filtered,"S17")
plot_all_wavefront(data_filtered,"S18")
plot_all_wavefront(data_filtered,"S20")
```





