name: tsai
channels:
  - conda-forge
dependencies:
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ipython=8.22.2
  - jedi=0.19.1
  - libffi=3.4.2
  - libsqlite=3.45.2
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - openssl=3.2.1
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - prompt-toolkit=3.0.42
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.10.12
  - readline=8.2
  - setuptools=69.2.0
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - wcwidth=0.2.13
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - annotated-types==0.6.0
      - blis==0.7.11
      - carto-reader==0.0.12
      - catalogue==2.0.10
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - confection==0.1.4
      - contourpy==1.2.0
      - cramjam==2.8.3
      - cycler==0.12.1
      - cymem==2.0.8
      - et-xmlfile==1.1.0
      - fastai==2.7.14
      - fastcore==1.5.29
      - fastdownload==0.0.7
      - fastparquet==2024.2.0
      - fastprogress==1.0.3
      - filelock==3.13.1
      - fonttools==4.50.0
      - fsspec==2024.3.0
      - idna==3.6
      - imbalanced-learn==0.12.0
      - jinja2==3.1.3
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - langcodes==3.3.0
      - llvmlite==0.42.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - meshio==5.3.5
      - mpmath==1.3.0
      - murmurhash==1.0.10
      - networkx==3.2.1
      - numba==0.59.0
      - numpy==1.26.4
      - openpyxl==3.1.2
      - packaging==24.0
      - pandas==2.2.1
      - pillow==10.2.0
      - platformdirs==4.2.1
      - pooch==1.8.1
      - potpourri3d==1.0.0
      - preshed==3.0.9
      - psutil==5.9.8
      - pyarrow==15.0.2
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pymesh==1.0.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pyts==0.13.0
      - pytz==2024.1
      - pyvista==0.43.7
      - pyyaml==6.0.1
      - requests==2.31.0
      - rich==13.7.1
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - scooby==0.10.0
      - seaborn==0.13.2
      - smart-open==6.4.0
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - sympy==1.12
      - thinc==8.2.3
      - threadpoolctl==3.3.0
      - torch==2.2.1
      - torchvision==0.17.1
      - tqdm==4.66.2
      - tsai==0.3.9
      - typer==0.9.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - vtk==9.3.0
      - wasabi==1.1.2
      - weasel==0.3.4
      - pyarrow==16.0.0
      - pyvista==0.43.7
      - carto_reader==0.0.12
