name: ecg
channels:
  - conda-forge
dependencies:
  - asttokens=2.4.1
  - aws-c-auth=0.7.11
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.12
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.1
  - aws-c-http=0.8.0
  - aws-c-io=0.14.0
  - aws-c-mqtt=0.10.1
  - aws-c-s3=0.4.9
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.0
  - aws-sdk-cpp=1.11.210
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.26.0
  - ca-certificates=2024.2.2
  - cachecontrol=0.13.1
  - cachecontrol-with-filecache=0.13.1
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - cleo=2.1.0
  - colorama=0.4.6
  - contourpy=1.2.0
  - crashtest=0.4.1
  - cycler=0.12.1
  - cython=3.0.8
  - decorator=5.1.1
  - distlib=0.3.8
  - dulwich=0.21.7
  - exceptiongroup=1.2.0
  - filelock=3.13.1
  - fonttools=4.47.2
  - freetype=2.12.1
  - gflags=2.2.2
  - glog=0.6.0
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipython=8.20.0
  - jaraco.classes=3.3.0
  - jedi=0.19.1
  - keyring=24.3.0
  - kiwisolver=1.4.5
  - klib=1.1.2
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libopenblas=0.3.26
  - libparquet=15.0.0
  - libpng=1.6.39
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.4
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - more-itertools=10.2.0
  - msgpack-python=1.0.7
  - munkres=1.1.4
  - ncurses=6.4
  - numpy=1.26.3
  - openjpeg=2.5.0
  - openssl=3.2.1
  - orc=1.9.2
  - packaging=23.2
  - parso=0.8.3
  - patsy=0.5.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.2
  - pkginfo=1.9.6
  - platformdirs=3.11.0
  - plotly=5.18.0
  - poetry=1.7.1
  - poetry-core=1.8.1
  - poetry-plugin-export=1.6.0
  - prompt-toolkit=3.0.42
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=15.0.0
  - pycparser=2.21
  - pygments=2.17.2
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pyparsing=3.1.1
  - pyproject_hooks=1.0.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-build=1.0.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-installer=0.7.0
  - python-tzdata=2023.4
  - python_abi=3.11
  - pytz=2023.4
  - rapidfuzz=3.6.1
  - re2=2023.06.02
  - readline=8.2
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - scipy=1.12.0
  - screeninfo=0.8.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=69.0.3
  - shellingham=1.5.4
  - six=1.16.0
  - snappy=1.1.10
  - statsmodels=0.14.1
  - tenacity=8.2.3
  - tk=8.6.13
  - tomli=2.0.1
  - tomlkit=0.12.3
  - tornado=6.3.3
  - traitlets=5.14.1
  - trove-classifiers=2024.1.31
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=2.2.0
  - virtualenv=20.25.0
  - wcwidth=0.2.13
  - wheel=0.42.0
  - xattr=0.10.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - anyio==4.2.0
      - appnope==0.1.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - bokeh==2.4.3
      - bottleneck==1.3.7
      - click==7.1.2
      - cloudpickle==3.0.0
      - comm==0.2.1
      - dask==2.30.0
      - dataprep==0.4.1
      - debugpy==1.8.0
      - defusedxml==0.7.1
      - distributed==2.30.1
      - entrypoints==0.4
      - et-xmlfile==1.1.0
      - executing==0.8.3
      - flask==1.1.4
      - flask-cors==3.0.10
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - future==0.18.3
      - ipykernel==6.29.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.8.1
      - isoduration==20.11.0
      - itsdangerous==1.1.0
      - jinja2==2.11.3
      - joblib==1.3.2
      - jsonpath-ng==1.6.1
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==7.4.9
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==1.1.7
      - levenshtein==0.12.0
      - llvmlite==0.42.0
      - locket==1.0.0
      - markupsafe==2.0.1
      - metaphone==0.6
      - mistune==0.8.4
      - multidict==6.0.5
      - nbclassic==1.0.0
      - nbclient==0.5.13
      - nbconvert==6.4.5
      - nbformat==5.9.2
      - nest-asyncio==1.6.0
      - nltk==3.6.3
      - notebook==6.5.6
      - notebook-shim==0.2.3
      - numba==0.59.0
      - openpyxl==3.1.2
      - overrides==7.7.0
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - partd==1.4.1
      - ply==3.11
      - probableparsing==0.0.1
      - prometheus-client==0.19.0
      - psutil==5.9.8
      - pydantic==1.10.14
      - python-crfsuite==0.9.10
      - python-json-logger==2.0.7
      - python-stdnum==1.19
      - pyyaml==6.0.1
      - pyzmq==24.0.1
      - referencing==0.33.0
      - regex==2020.11.13
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.17.1
      - scikit-learn==1.4.1.post1
      - send2trash==1.8.2
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - stack-data==0.5.1
      - stumpy==1.12.0
      - tblib==3.0.0
      - terminado==0.18.0
      - testpath==0.6.0
      - threadpoolctl==3.3.0
      - toolz==0.12.1
      - tqdm==4.66.1
      - tsfresh==0.20.2
      - types-python-dateutil==2.8.19.20240106
      - uri-template==1.3.0
      - usaddress==0.5.10
      - varname==0.8.3
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==1.0.1
      - widgetsnbextension==3.6.6
      - wordcloud==1.9.3
      - xgboost==2.0.3
      - yarl==1.9.4
      - zict==3.0.0
